#ifndef ASCIISYMBOLS_H
#define ASCIISYMBOLS_H

#include <cstdint>

//Enums for ASCII tile ID (ASYM stands for Ascii SYMbol)
enum AsciiSymbol : uint8_t {
	ASYM_BLANK = 0,
	ASYM_SMILE_THIN, ASYM_SMILE_FILLED, ASYM_HEART, ASYM_SQUARE_DIAMOND,
	ASYM_DOT_LARGE = 7, ASYM_REVERSE_DOT_LARGE,
	ASYM_ARROW_UP = 24, ASYM_ARROW_DOWN, ASYM_ARROW_RIGHT, ASYM_ARROW_LEFT,
	ASYM_SPACE = 32, ASYM_EXCLAMATION, ASYM_DOUBLE_QUOTES, ASYM_HASHTAG, ASYM_DOLLAR, ASYM_PERCENT,
	ASYM_AMPERSAND, ASYM_UFO, ASYM_LEFT_PARENTHESIS, ASYM_RIGHT_PARENTHESIS, ASYM_ASTERISK,
	ASYM_PLUS, ASYM_COMMA, ASYM_EM_DASH, ASYM_PERIOD, ASYM_FORWARD_SLASH,
	ASYM_ZERO, ASYM_ONE, ASYM_TWO, ASYM_THREE, ASYM_FOUR, ASYM_FIVE, ASYM_SIX,
	ASYM_SEVEN, ASYM_EIGHT, ASYM_NINE,
	ASYM_COLON, ASYM_SEMICOLON, ASYM_LESS_THAN, ASYM_EQUAL, ASYM_GREATER_THAN,
	ASYM_QUESTION_MARK, ASYM_AT_SIGN,
	ASYM_AT = 64,
	ASYM_DOTS = 176,
	ASYM_BLOCK = 219,
	ASYM_DOT = 249, ASYM_SMALL_DASH,
	ASYM_RETICLE = 255
};

#endif
